### ISSUE TITLE
Cannot parse data "STATE

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.sonoff#109]
Sometimes following log occurs:

`

host.IoBrokerSmartHome | 2019-12-05 10:30:29.456 | error | Caught by controller[0]: at DestroyableTransform.onreadable (/opt/iobroker/node_modules/duplexify/index.js:134:10)
-- | -- | -- | --
host.IoBrokerSmartHome | 2019-12-05 10:30:29.456 | error | Caught by controller[0]: at Connection.Duplexify._forward (/opt/iobroker/node_modules/duplexify/index.js:170:26)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at Connection.Readable.push (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at readableAddChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at addChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at Connection.emit (events.js:198:13)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at Connection.emit (events.js:198:13)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.455 | error | Caught by controller[0]: at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1535:21)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.454 | error | Caught by controller[0]: at receivedTopic (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1055:30)
host.IoBrokerSmartHome | 2019-12-05 10:30:29.454 | error | Caught by controller[0]: TypeError: Cannot read property 'topic' of undefined
sonoff.0 | 2019-12-05 10:30:28.376 | error | at DestroyableTransform.onreadable (/opt/iobroker/node_modules/duplexify/index.js:134:10)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.Duplexify._forward (/opt/iobroker/node_modules/duplexify/index.js:170:26)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.Readable.push (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at readableAddChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at addChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.emit (events.js:198:13)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.emit (events.js:198:13)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1535:21)
sonoff.0 | 2019-12-05 10:30:28.376 | error | at receivedTopic (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1055:30)
sonoff.0 | 2019-12-05 10:30:28.376 | error | (3788) TypeError: Cannot read property 'topic' of undefined
sonoff.0 | 2019-12-05 10:30:28.375 | error | (3788) uncaught exception: Cannot read property 'topic' of undefined
sonoff.0 | 2019-12-05 10:30:28.369 | warn | (3788) Cannot parse data "STATE": _{"Time":"2019-12-05T10:30:01","Uptime":"1T15:03:37","UptimeSec":140617,"Heap":23,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":7,"POWER":"ON","Wifi":{"A

`

**Comment by homecineplexx** [comment]
here is the complete log:
`
2019-12-07 16:10:13.308  - ESC[33mwarnESC[39m: sonoff.0 (17290) Cannot parse data "SENSOR": _{"Time":"2019-12-07T16:09:46","ENERGY":{"TotalStartTime":"2018-12-28T11:21:03","Total":325.006,"Yesterday":0.024,"Today":1.370,"Period":0,"Power":2,"ApparentPow0�^B^@^Qtele/sonoff/STATE{"Time":"2019-12-07T16:10:00","Uptime":"0T15:57:07"_ - SyntaxError: Unexpected token ^B in JSON at position 162
2019-12-07 16:10:13.321  - ESC[31merrorESC[39m: sonoff.0 (17290) uncaught exception: Cannot read property 'topic' of undefined
2019-12-07 16:10:13.322  - ESC[31merrorESC[39m: sonoff.0 (17290) TypeError: Cannot read property 'topic' of undefined
    at receivedTopic (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1055:30)
    at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:1535:21)
    at Connection.emit (events.js:198:13)
    at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
    at Connection.emit (events.js:198:13)
    at addChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Connection.Readable.push (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Connection.Duplexify._forward (/opt/iobroker/node_modules/duplexify/index.js:170:26)
    at DestroyableTransform.onreadable (/opt/iobroker/node_modules/duplexify/index.js:134:10)
2019-12-07 16:10:14.326  - ESC[33mwarnESC[39m: sonoff.0 (17290) Terminated (UNCAUGHT_EXCEPTION): Without reason
`

**Comment by Apollon77** [comment]
Also da sind eindeutug ungültige Zeichen im Inhalt ... Was ist dieses 

ApparentPow0�^B^@^Qtele/sonoff

Bitte device prüfen was das sendet!

**Comment by homecineplexx** [comment]
ja ich hab das gesehen, allerdings weiß ich nicht, warum der Sonoff dann ganz plötzlich solche Schmierzeichen schickt.
