### ISSUE TITLE
no mqtt message show up for my RF Bridge

### ISSUE THREAD

**Issue by haegar33** [ioBroker/ioBroker.sonoff#49]
This might be a stupid error or simply missing information: when installing the sonoff adapter I don't see my RF Bridge showing up. There is a connection to my local MQTT broker (on my NAS as well as the iobroker instance) and using the adapter "MQTT" I can even see some message. But not with this adapter!
For example my bridge sends a tele status:
tele/sonoff/STATE = {"Time":"2018-06-19T11:32:24","Uptime":"4T18:19:15","Vcc":3.143,"Wifi":{"AP":1,"SSId ......

which I can see from the Tasmota Web Interface console
Do I need to manually setup something? I would have assumed that mqtt topics like tele/sonoff should appear automatically?

The log shows a lot of errors:

> 

sonoff.0 | 2018-06-19 11:43:02.359 | error | at process._tickCallback (node.js:428:17)
-- | -- | -- | --
sonoff.0 | 2018-06-19 11:43:02.359 | error | at nextTickCallbackWith3Args (node.js:522:9)
sonoff.0 | 2018-06-19 11:43:02.359 | error | at net.js:1398:9
sonoff.0 | 2018-06-19 11:43:02.359 | error | at listen (net.js:1289:10)
sonoff.0 | 2018-06-19 11:43:02.359 | error | at Server._listen2 (net.js:1253:14)
sonoff.0 | 2018-06-19 11:43:02.359 | error | at exports._exceptionWithHostPort (util.js:930:20)
sonoff.0 | 2018-06-19 11:43:02.359 | error | at Object.exports._errnoException (util.js:907:11)
sonoff.0 | 2018-06-19 11:43:02.359 | error | Error: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2018-06-19 11:43:02.353 | error | uncaught exception: listen EADDRINUSE 0.0.0.0:1883

**Comment by haegar33** [comment]
Problem solved. I was not aware that this adapter is also a MQTT broker, not only a client. It conflicted with my existing broker on the same host. After removing the adapter works as expected.

It would be nice idea to mention this in the readme.md? Would have saved me hours of troubleshooting. Thanks!
