### ISSUE TITLE
Connection to MQTT-Adapter not possible

### ISSUE THREAD

**Issue by kvpdesperado** [ioBroker/ioBroker.sonoff#5]
Connection to MQTT-Adapter not possible.

The following error messages are shown in the log.

```
sonoff.0 | 2017-11-04 15:32:54.404 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
sonoff.0 | 2017-11-04 15:32:54.404 | error | at _combinedTickCallback (internal/process/next_tick.js:83:11)
sonoff.0 | 2017-11-04 15:32:54.404 | error | at net.js:1404:9
sonoff.0 | 2017-11-04 15:32:54.404 | error | at listen (net.js:1294:10)
sonoff.0 | 2017-11-04 15:32:54.404 | error | at Server._listen2 (net.js:1258:14)
sonoff.0 | 2017-11-04 15:32:54.404 | error | at exports._exceptionWithHostPort (util.js:1043:20)
sonoff.0 | 2017-11-04 15:32:54.404 | error | at Object.exports._errnoException (util.js:1020:11)
sonoff.0 | 2017-11-04 15:32:54.404 | error | Error: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2017-11-04 15:32:54.402 | error | uncaught exception: listen EADDRINUSE 0.0.0.0:1883
```

**Comment by GermanBluefox** [comment]
You are trying to run on the same system sonoff and MQTT broker together. Both of them use port 1883 as default.
To start both instances on the same system you must change one port to other value, e.g. 1884 and of course all your MQTT clients too.
