### ISSUE TITLE
adapter enters crash loop when client's password is missing

### ISSUE THREAD

**Issue by jlegen** [ioBroker/ioBroker.sonoff#80]
log shows this when a tasmota client with missing password tries to access; adapter restarts afterwards
```
sonoff.0 | 2019-01-19 16:09:37.326 | info | terminating
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.emit (events.js:211:7)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at emitOne (events.js:116:13)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Object.onceWrapper (events.js:315:30)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.<anonymous> (/usr/local/iobroker/node_modules/mqtt-connection/connection.js:53:12)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.emit (events.js:211:7)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at emitOne (events.js:116:13)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.emitPacket (/usr/local/iobroker/node_modules/mqtt-connection/connection.js:10:8)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.emit (events.js:211:7)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at emitOne (events.js:116:13)
sonoff.0 | 2019-01-19 16:09:36.823 | error | at Connection.client.on.packet (/usr/local/iobroker/node_modules/iobroker.sonoff/lib/server.js:1554:34)
sonoff.0 | 2019-01-19 16:09:36.823 | error | TypeError: Cannot read property 'forEach' of undefined
sonoff.0 | 2019-01-19 16:09:36.823 | error | uncaught exception: Cannot read property 'forEach' of undefined
```

**Comment by GermanBluefox** [comment]
Please test 2.3.0
